### ISSUE TITLE
Compiles with errors in Xcode 9 (Swift version 3.2)

### ISSUE THREAD

**Issue by michaeltansg** [yahoojapan/SwiftyXMLParser#9] opened 2017-06-08 19:45 UTC
Compiling the project with Xcode 9 using Swift version 3.2, I get the following errors in Accessor.swift inlined below:
```
        public func makeIterator() -> AnyIterator<Accessor> {
            let generator: [Element]
            switch self {
            case .failure(_):
                generator = [Element]()
            case .singleElement(let element):
                generator = [element] // Cannot convert value of type 'XML.Element' to expected element type 'XML.Accessor'
            case .sequence(let elements):
                generator = elements // Cannot assign value of type '[XML.Element]' to type '[XML.Accessor.Element]' (aka 'Array<XML.Accessor>')
            }
            var index = 0
            return AnyIterator {
                let nextAccessor: Accessor?
                if index < generator.count {
                    nextAccessor = Accessor(generator[index]) // Cannot invoke initializer for type 'XML.Accessor' with an argument list of type '(XML.Accessor.Element)'
                    index += 1
                } else {
                    nextAccessor = nil
                }
                return nextAccessor
            }
        }

```
This one is beyond me. Does anyone know how we can fix this?

EDIT: Just confirmed with Apple engineer @WWDC that this could be a bug where the type inference is incorrect. To workaround:
```
        public func makeIterator() -> AnyIterator<Accessor> {
            let generator: [XML.Element]
            switch self {
            case .failure(_):
                generator = []
                .
                .
       }
```

I can not confirm if this establishes the required behaviour for SwiftyXMLParser.

EDIT: I ran the unit tests on the project and it passes.

**Comment by kazuhiro4949** [comment] 2017-06-09 01:22
Thank you for your report. I'll check later.

**Comment by kazuhiro4949** [comment] 2017-06-09 11:27
It seems that the compiler error is not a bug but Xcode9's feature. (thx! @tattn)

This document says Sequence protocol declares 'Element'. So it collides with 'XML.Accessor.Element'.
https://developer.apple.com/documentation/swift/sequence/2908099-element

I'll merge the pull-request after checking it, thx!

**Comment by ElizaSapir** [comment] 2017-06-11 11:06
Hey @kazuhiro4949, 

I have the same issue, when new version will be released? 
Tested your fix and it works for me.

Thanks,

Eliza

**Comment by kazuhiro4949** [comment] 2017-06-12 09:08
@michaeltansg This fix is ok. Could you make pull-request to "yahoojapan/SwiftyXMLParser" ?
https://github.com/michaeltansg/SwiftyXMLParser/pull/1

**Comment by michaeltansg** [comment] 2017-06-13 08:14
Submitted the pull request.

**Comment by ElizaSapir** [comment] 2017-06-13 19:09
@kazuhiro4949  can you tag new version via cocoapods? with the above fix?

Thanks,
Eliza

**Comment by kazuhiro4949** [comment] 2017-06-14 08:44
Thank you, @michaeltansg and @ElizaSapir !
I released the new version (3.0.3). It is distributed on cocoapods, too.

**Comment by bigearsenal** [comment] 2017-06-14 15:49
I just installed newest version (3.0.3), but i still got this error:
Cannot subscript a value of type 'XML.Accessor' with an index of type '(String, String)' when calling xml["root", "child1"]

**Comment by kazuhiro4949** [comment] 2017-06-15 06:13
@bigearsenal Which environment Is it compiled on?  I'll check the problem and fix it.

**Comment by bigearsenal** [comment] 2017-06-15 09:08
Thank you for responding. It's on Xcode 8.3, swift 3.2
It worked on previous version. I haven't changed my code since then
But now i have to change syntax to xml["root"]["child1"]

**Comment by kazuhiro4949** [comment] 2017-06-15 10:23
@bigearsenal 
I'm sorry for the trouble. 
The latest version has a update only for Xcode9-beta. 
Could you use version 3.0.2 until I fix the issue you reported?

**Comment by bigearsenal** [comment] 2017-06-15 12:36
@kazuhiro4949  Ok. Thank you :)

**Comment by kazuhiro4949** [comment] 2017-10-01 09:50
I wrote which Xcode each version supports in release notes. If you have a trouble, feel free to reopen.
https://github.com/yahoojapan/SwiftyXMLParser/releases

**Closed as completed by kazuhiro4949** 2017-10-01 09:50 UTC
